### ISSUE TITLE
User::logout() Sorunu

### ISSUE THREAD

**Issue by rmzonl** [znframework/Final#165]
Merhabalar. rememberMe değişkeni true olarak  (**User::login(username, password, true)**)  giriş yapan kullanıcı, User::logout() ile çıkış yapmak istediğinde kullanıcı çıkış yapamıyor. Ayrıca rememberMe true yada false hangisi olursa olsun User::logout() çalıştığında Sessions'daki password verisi silinmiyor. Ozan hocam konuyla ilgili dönüş yapabilirseniz daha detaylı olarak sorunu anlatabilirim. İyi çalışmalar dilerim.

**Comment by ozanuykun** [comment]
Muhtemelen session ayarları ile ilgili bir problem yaşıyor olabilirsin. Çünkü yıllardır kullandığımız ve bu konuda üzerinde herhangi bir düzenleme yapmadığımız yöntemler bahsettiğin. Şuanda bütün geliştirdiğimiz projelerde aktif olarak kullanıyoruz bu özellikleri. Session keyler'i kontrol et.

**Comment by rmzonl** [comment]
Ozan hocam telegram yada facebook üzerinden iletişim kurabilirsek sorunu bizzat göstermek isterim.

**Comment by rmzonl** [comment]
Hocam sorunun kaynağı Cookie ayarları ile anladığım kadarıyla. Config::set('Storage', 'cookie', $settings) ile belirlenen ayarlar Internal/package-storage/Cookie.php içerisindeki $this->config değişkenine aktarılmıyor. Ekran görüntüsü mevcut.

![config-get-storage-cookie](https://user-images.githubusercontent.com/16738804/190871211-3520213f-eb72-49e5-9abb-fe051f2c9a70.png)

**Comment by ozanuykun** [comment]
Sorunun kaynağı anlaşıldı. Teşekkürler.

**Comment by rmzonl** [comment]
Hocam bahsettiğim sorun devam etmektedir.
PRoje Container Yapım:
'BackEnd'            => 'FrontEnd'

Backend tarafında bir admin login olunca, Cookie::domain(DOMAIN)->insert('AdminIsLogin', true); şeklinde bir çerez tanımlıyorum.
Frontend tarafında ilgili çerezi yakalamak için ya Cookie::domain(DOMAIN)->select('AdminIsLogin); yazıyorum ya da ->domain metodunu kullanmayacaksam Config::set ile her iki taraf için de (backend ve frontend) domain tanımlıyorum.

Sorun şu ki, Config::set ile domain tanımlarsam yada Cookie::domain(DOMAIN)->.. şeklinde domain tanımlarsam; User::logout() çıkış kesinlikle çıkış yapmıyor. password çerezini siliyor ancak username çerezini silmiyor. 
Bilginize..

**Comment by ozanuykun** [comment]
Config::set Oturum açmadan sonra devreye giriyorsa o ayarı tekrar önceki ayarlarla set edilmeden logout yapılamayacaktır. Config::set derken bu yöntemini kullandığını anlıyorum. 

Şimdi sorunun ana nedeni Config::setin user::login den sonra kullanıyor olması. Dolayısı ile farklı konuma oluşturulan çerez daha sonrasında user logoutla silinmek isteniyor. O nedenle user logouttan önce domaini ilk haline yeniden set etmen gerekir.

**Comment by rmzonl** [comment]
Hocam yalnız Config::set metodunu başlangıç kontrolcüde kullanıyorum. Hem Back-end hem de Front-end tarafında ortak kullanılan external başlangıç kontrolcüsünde. İşin garip tarafı logout yaptıktan sonra cookie print ediyorum ve password silinmiş oluyor cookieden. Ancak username silinmemiş oluyor. Sizin dediğiniz gibi olsa password verisini de silememesi gerekmez mi? Ayrıca password silinmesine rağmen user hala login konumda görünüyor. User::login içindeki cookie::insert metodu config::set ile belirtilen ayarları kullanmıyor olabilir mi?

**Comment by rmzonl** [comment]
Hocam sorun çözüldü. Cookie::domain(DOMAIN)->insert('data', $data); şeklinde veri insert edince ben bu veriyi çekerken de Cookie::domain(DOMAIN)->select('data') şeklinde domain belirterek çekiyordum. Bu işlem sırasında Cookie config'inde istemeden değişiklik yapmış oluyormuşum. Ancak başlangıç kontrolcüde Config::set ile domain belirtince yine aynı sorun oluyordu. Son güncellemenizden sonra her iki projenin de başlangıç kontrolcüsünde config::set ile domain belirtince her iki projeye de login oluyor user. bu da ilginç bir özellik oldu :)
