### ISSUE TITLE
Mongo Login Hatası

### ISSUE THREAD

**Issue by rilik26** [znframework/Final#166]
Merhabalar,

Post ile üye kaydı gerçekleştirebiliyorum.

if( Post::RegisterSubmit() )
                                        {
                                           $md5=md5(Post::password());
                                           $ekle=MDB::insert
                                           (
                                            'users',
                                            [ array
                                                (
                                                'username'=>Post::username(),
                                                'password'=>$md5 
                                                )
                                            ]);
                                           
                                           if( $ekle )
                                           {}
                                           else
                                           {
                                               echo '<script>Swal.fire("'.ML::select('error').'", "'.ML::select('register_error_1').'.", "error"); </script>'; 
                                           }
                                        }

Fakat üye girişi yaptıramıyorum.

if( Post::LoginSubmit() )
                                        {
                                            $status = User::login(Post::username(), Post::password());
                                            if( $status)
                                            {
                                                Redirect::action('Home/');
                                            }
                                            else
                                            {
                                                echo '<script>Swal.fire("'.ML::select('error').'", "'.ML::select('login_error_1').'.", "error"); </script>'; 
                                            }
                                        }

Nerde hata yapıyorum @ozanuykun

**Comment by ozanuykun** [comment]
şifre kendisi otomatik olarak şifrelenir. Sizin md5 ile şifrelemenize gerek yok. md5 kullandığınızda 2 kez şifreleme uygulamış oluyorsunuz. Şifreleme metotunu değiştirmek isterseniz Config/Auth.php de encode değerini değiştirmeniz yeterli olacaktır. Kolay gelsin.

**Comment by rilik26** [comment]
hem md5 hemde normal kayıt yaptım,
hem md5 hemde normal  girişle denedim fakat ne yazikki login yapamıyorum.

```
$ekle=MDB::insert
                                           (
                                            'users',
                                            [ array
                                                (
                                                'username'=>Post::username(),
                                                'password'=>Post::password() 
                                                )
                                            ],
$status = User::login(Post::username(), Post::password(), Post::rememberMe());
```

sonuç olumsuz

```
$ekle=MDB::insert
                                           (
                                            'users',
                                            [ array
                                                (
                                                'username'=>Post::username(),
                                                'password'=>$md5 
                                                )
                                            ],
$status = User::login(Post::username(), $md5 , Post::rememberMe());
```

sonuç olumsuz @ozanuykun

**Comment by ozanuykun** [comment]
İçeriğin Mongo ile alakalı olduğunu yeni farkettim. User işlemleri DB ile kullanılabilir sadece. Mongo ile çalışmaz.
