### ISSUE TITLE
Apache 2.4 internal server error 500 hatası hk.

### ISSUE THREAD

**Issue by BursaYazilimCom** [znframework/Final#167]
Kolay gelsin Apache 2.4 versiyonunda mecvut .htaccess dosyaları 500 hatası verdiriyor.

Resources klasöründe ki .htaccess dosyasını 
Require all granted
Project klasöründe ki .htaccess dosyasını 
Require all denied

Ve 
Seetings/Htaccess.php içerisinde 
'FilesMatch "^(?i:docker\-compose\.yml|Dockerfile)$"' => ['deny from all'] 

Koşulunu 

'FilesMatch "^(?i:docker\-compose\.yml|Dockerfile)$"' => ['Require all denied'] 

olarak değiştirince sorun düzeldi

**Comment by ozanuykun** [comment]
Evet apache versiyonunda yer alan kod farklılıklarından dolayı mecburen bu düzenlemeler gerekebiliyor.
